columnn_width=999999
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 4
quote_style = "ForceDouble"
call_parentheses = "Always"
collpase_simple_statement = "FunctionOnly"

[sort_requires]
enabled = true
