git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never

keybinding:
  universal:
    quit: '<c-q>'
    return: 'q'

gui:
  theme:
    selectedLineBgColor:
      - reverse
    selectedRangeBcColor:
      - reverse
